#!/usr/bin/env python3
#
# Copyright 2026, Unikie
#
# SPDX-License-Identifier: Apache-2.0
#

"""Generate CAmkES component identity metadata for mux introspection."""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


COMPONENT_RE = re.compile(r"\bcomponent\s+([A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*;")


def _sanitize_macro(name):
    token = re.sub(r"[^A-Za-z0-9_]", "_", name)
    token = re.sub(r"_+", "_", token).strip("_")
    if not token:
        token = "STREAM"
    if token[0].isdigit():
        token = "_" + token
    return token.upper()


def _json_escape_for_c(value):
    return json.dumps(value)


def _run_cpp(args):
    cmd = [args.cpp, "-P"]
    for include in args.cpp_include:
        cmd.append("-I" + str(include))
    cmd.extend(args.cpp_flag)
    cmd.append(str(args.camkes))
    try:
        return subprocess.run(
            cmd,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ).stdout
    except subprocess.CalledProcessError as err:
        if err.stderr:
            sys.stderr.write(err.stderr)
        raise SystemExit(err.returncode)


def _extract_block(text, keyword):
    match = re.search(r"\b" + re.escape(keyword) + r"\s*\{", text)
    if not match:
        raise ValueError(f"missing '{keyword} {{' block")

    start = match.end()
    depth = 1
    pos = start
    while pos < len(text):
        char = text[pos]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start:pos]
        pos += 1

    raise ValueError(f"unterminated '{keyword}' block")


def _composition_text(preprocessed):
    assembly = _extract_block(preprocessed, "assembly")
    return _extract_block(assembly, "composition")


def _component_instances(preprocessed):
    composition = _composition_text(preprocessed)
    streams = []
    seen = set()
    for match in COMPONENT_RE.finditer(composition):
        component_type, component_name = match.groups()
        if component_name in seen:
            raise ValueError(f"duplicate component instance '{component_name}'")
        seen.add(component_name)
        streams.append(
            {
                "stream_id": -1,
                "component": component_name,
                "type": component_type,
                "stream_id_source": "component.common.c",
                "direction": "unknown",
                "aliases": [],
            }
        )
    if not streams:
        raise ValueError("no component instances found in assembly composition")
    return streams


def _write_json(path, registry):
    path.write_text(json.dumps(registry, indent=2, sort_keys=True) + "\n")


def _write_header(path, registry):
    guard = _sanitize_macro(path.name) + "_"
    lines = [
        "/* Generated by generate_camkes_stream_registry.py. Do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#define VIRTIO_CAMKES_STREAM_INVALID (-1)",
    ]
    for stream in registry["streams"]:
        lines.append(
            "#define VIRTIO_CAMKES_STREAM_%s VIRTIO_CAMKES_STREAM_INVALID"
            % _sanitize_macro(stream["component"])
        )
    lines.extend(
        [
            "",
            "struct virtioso_camkes_stream_descriptor {",
            "    int32_t stream_id;",
            "    const char *component;",
            "    const char *type;",
            "    const char *stream_id_source;",
            "    const char *direction;",
            "};",
            "",
            "extern const struct virtioso_camkes_stream_descriptor",
            "    virtioso_camkes_stream_registry[];",
            "extern const size_t virtioso_camkes_stream_registry_count;",
            "extern const char virtioso_camkes_stream_registry_json[];",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def _write_c(path, header_name, registry):
    lines = [
        "/* Generated by generate_camkes_stream_registry.py. Do not edit. */",
        f'#include "{header_name}"',
        "",
        "const struct virtioso_camkes_stream_descriptor",
        "virtioso_camkes_stream_registry[] = {",
    ]
    for stream in registry["streams"]:
        lines.append(
            '    {%d, "%s", "%s", "%s", "%s"},'
            % (
                stream["stream_id"],
                stream["component"],
                stream["type"],
                stream["stream_id_source"],
                stream["direction"],
            )
        )
    lines.extend(
        [
            "};",
            "",
            "const size_t virtioso_camkes_stream_registry_count =",
            "    sizeof(virtioso_camkes_stream_registry) /",
            "    sizeof(virtioso_camkes_stream_registry[0]);",
            "",
            "const char virtioso_camkes_stream_registry_json[] =",
        ]
    )
    registry_json = json.dumps(registry, sort_keys=True)
    lines.append("    %s;" % _json_escape_for_c(registry_json))
    lines.append("")
    path.write_text("\n".join(lines))


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("--camkes", required=True, type=Path)
    parser.add_argument("--name", required=True)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--cpp", default="cpp")
    parser.add_argument("--cpp-include", action="append", default=[], type=Path)
    parser.add_argument("--cpp-flag", action="append", default=[])
    args = parser.parse_args(argv)

    preprocessed = _run_cpp(args)
    streams = _component_instances(preprocessed)
    registry = {
        "schema": "virtioso.camkes_component_identity.v1",
        "name": args.name,
        "source": str(args.camkes),
        "streams": streams,
    }

    args.out_dir.mkdir(parents=True, exist_ok=True)
    _write_json(args.out_dir / "console-stream-registry.json", registry)
    _write_header(args.out_dir / "console_stream_ids.h", registry)
    _write_c(args.out_dir / "console_stream_registry.c", "console_stream_ids.h", registry)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
