function(VirtiosoGenerateCAmkESStreamRegistry name camkes_config)
    cmake_parse_arguments(
        PARSE_ARGV
        2
        STREAM_REGISTRY
        ""
        ""
        "CPP_FLAGS;CPP_INCLUDES"
    )

    if(STREAM_REGISTRY_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown arguments: ${STREAM_REGISTRY_UNPARSED_ARGUMENTS}")
    endif()

    if(IS_ABSOLUTE "${camkes_config}")
        set(stream_registry_camkes "${camkes_config}")
    else()
        set(stream_registry_camkes "${CMAKE_CURRENT_LIST_DIR}/${camkes_config}")
    endif()

    if(NOT EXISTS "${stream_registry_camkes}")
        message(FATAL_ERROR "CAmkES file not found: ${stream_registry_camkes}")
    endif()

    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    find_program(VIRTIO_CAMKES_CPP cpp)
    if(NOT VIRTIO_CAMKES_CPP)
        message(FATAL_ERROR "cpp not found; cannot generate CAmkES stream registry")
    endif()

    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" stream_registry_target "${name}")
    set(stream_registry_out_dir
        "${CMAKE_BINARY_DIR}/generated/virtioso_camkes_stream_registry/${stream_registry_target}"
    )
    set(stream_registry_json "${stream_registry_out_dir}/console-stream-registry.json")
    set(stream_registry_header "${stream_registry_out_dir}/console_stream_ids.h")
    set(stream_registry_source "${stream_registry_out_dir}/console_stream_registry.c")
    file(MAKE_DIRECTORY "${stream_registry_out_dir}")
    if(NOT EXISTS "${stream_registry_header}")
        file(WRITE "${stream_registry_header}" "/* Placeholder; regenerated by virtioso stream registry build rule. */\n")
    endif()
    if(NOT EXISTS "${stream_registry_source}")
        file(WRITE "${stream_registry_source}" "/* Placeholder; regenerated by virtioso stream registry build rule. */\n")
    endif()
    set_source_files_properties(
        "${stream_registry_header}"
        "${stream_registry_source}"
        PROPERTIES GENERATED TRUE
    )

    set(stream_registry_includes
        "${CMAKE_CURRENT_LIST_DIR}"
        "${CMAKE_CURRENT_SOURCE_DIR}"
        "${VIRTIOSO_CAMKES_VM_DIR}"
        "${VIRTIOSO_MUX_SOURCE_DIR}/sel4"
        ${STREAM_REGISTRY_CPP_INCLUDES}
        "${CAMKES_VM_DIR}/components/VM"
        "${CAMKES_VM_DIR}/components/VM/configurations"
        "${CAMKES_VM_DIR}/components/VM_Arm"
        "${CAMKES_VM_DIR}/components/VM_Arm/configurations"
    )

    set(stream_registry_include_args "")
    foreach(include_dir IN LISTS stream_registry_includes)
        if(include_dir)
            list(APPEND stream_registry_include_args --cpp-include "${include_dir}")
        endif()
    endforeach()

    set(stream_registry_cpp_flag_args "")
    foreach(cpp_flag IN LISTS STREAM_REGISTRY_CPP_FLAGS)
        if(cpp_flag)
            list(APPEND stream_registry_cpp_flag_args "--cpp-flag=${cpp_flag}")
        endif()
    endforeach()

    add_custom_command(
        OUTPUT
            "${stream_registry_json}"
            "${stream_registry_header}"
            "${stream_registry_source}"
        COMMAND
            ${Python3_EXECUTABLE}
            "${VIRTIOSO_MUX_SOURCE_DIR}/tools/generate_camkes_stream_registry.py"
            --camkes "${stream_registry_camkes}"
            --name "${name}"
            --out-dir "${stream_registry_out_dir}"
            --cpp "${VIRTIO_CAMKES_CPP}"
            ${stream_registry_include_args}
            ${stream_registry_cpp_flag_args}
        DEPENDS
            "${stream_registry_camkes}"
            "${VIRTIOSO_MUX_SOURCE_DIR}/tools/generate_camkes_stream_registry.py"
        COMMENT "Generating CAmkES stream registry for ${name}"
        VERBATIM
    )

    add_custom_target(
        "virtioso_camkes_stream_registry_${stream_registry_target}"
        ALL
        DEPENDS
            "${stream_registry_json}"
            "${stream_registry_header}"
            "${stream_registry_source}"
    )

    set(VIRTIO_CAMKES_STREAM_REGISTRY_JSON "${stream_registry_json}" PARENT_SCOPE)
    set(VIRTIO_CAMKES_STREAM_REGISTRY_HEADER "${stream_registry_header}" PARENT_SCOPE)
    set(VIRTIO_CAMKES_STREAM_REGISTRY_SOURCE "${stream_registry_source}" PARENT_SCOPE)
endfunction()
